version: '3.8'

services:
  database:
    container_name: wh_database
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    container_name: wh_php
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '9000:9000'
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_START_WITH_REQUEST: ${XDEBUG_START_WITH_REQUEST:-no}
    volumes:
      - ./:/var/www/project
      - symfony_var_cache:/var/www/project/var/cache
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - database

  nginx:
    container_name: wh_nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/project:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  redis:
    image: redis:7-alpine
    container_name: wh_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

    #5672 – Messenger - RabbitMQ communication:
    #15672 – panel (http://localhost:15672
    #login: guest / guest)
    #PHP host: rabbitmq (service name!)
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: wh_rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck: # we add healthcheck to prevent running worker before rabbitmq fully works
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 2s
      retries: 5

  worker:
    container_name: wh_worker
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    command: php bin/console messenger:consume async -vv --time-limit=3600 --memory-limit=256M
    volumes:
      - ./:/var/www/project
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always

  cron:
    container_name: wh_cron
    build:
      context: .
      dockerfile: docker/cron/Dockerfile
    environment:
      MESSENGER_TRANSPORT_DSN: ${MESSENGER_TRANSPORT_DSN}
    volumes:
      - ./:/var/www/project
      - ./docker/cron/cronjobs.cron:/etc/cron.d/cronjobs
    command: sh -c "touch /var/www/project/var/log/cron.log && chmod 0644 /etc/cron.d/cronjobs && cron -f"
    depends_on:
      - rabbitmq
      - database

volumes:
  symfony_var_cache:
  db_data:
  redis_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
